### PR TITLE
Add cy (Welsh) profile to langdetect

### PR DESCRIPTION
**Pull request by techiaith**
I had originally made this pull request to the [Java project](https://code.google.com/p/language-detection/issues/detail?id=76), but since it seems that project is dead, and with Google Code closing down I thought it would be worth adding the Welsh profile to this project as well.

Cheers

### CODE REVIEW

**Comment by Mimino666** [comment]
Please describe how you generated the file, so I can check the correctness of it.
Thanks

**Comment by techiaith** [comment]
Sure.

The data has come from the [Welsh Wikipedia](http://cy.wikipedia.org/wiki/Hafan) and the [Proceedings of the National Assembly for Wales](http://www.corpws.org/proceedings-of-the-national-assembly-for-wales/?lang=en) (this is a corpws of Welsh transcripts of everything said in the government here, we have scraped this from their site - with their permission).

I created the file using the java tools from the lang-detect project. I followed the instructions [in the wiki](https://code.google.com/p/language-detection/wiki/Tools)
```
java -jar lib/langdetect.jar --genprofile -d [directory path] [language codes]
```

If you want to test the profile, you can use our API (which uses this Python package) with a special API I have set up for you:

https://api.techiaith.org/langdetect/v1/?api_key=9c6f0403-1a96-4d76-a426-63c9e4b7ed61&text=Mae%27r%20Cynulliad%20Cenedlaethol%20yn%20bedwerydd%20ar%20y%20rhestr%20o%27r%20lleoedd%20mwyaf%20cyfeillgar%20i%20bobl%20LGB%20weithio%20yn%20y%20DU

Change the `text` parameter to whatever you want. You could eg. use content from the Welsh government site:
http://www.cynulliad.cymru/cy/Pages/Hafan.aspx

**Comment by Mimino666** [comment]
Merged and increased langdetect to version 1.0.4.

Thank you for addition.

**Comment by techiaith** [comment]
Great, thanks :)

**Pull request merged**
